// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace POLTest1.Tests.SettingsAPI
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Settings", SourceFile="Tests\\Settings API\\Settings.feature", SourceLine=0)]
    public partial class SettingsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Settings.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Settings", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("To Verify the GET request of Settings API using SettingsID", new string[] {
                "happypath"}, SourceLine=3)]
        public virtual void ToVerifyTheGETRequestOfSettingsAPIUsingSettingsID()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To Verify the GET request of Settings API using SettingsID", new string[] {
                        "happypath"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "SettingsID"});
            table1.AddRow(new string[] {
                        "1649"});
#line 5
 testRunner.Given("Provided with the valid SettingsID.", ((string)(null)), table1, "Given ");
#line 8
 testRunner.When("I send a GET request to fetch settings details.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.Then("The valid settings details should be displayed.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("To Verify the Delete request of Settings API using SettingsID", new string[] {
                "happypath"}, SourceLine=11)]
        public virtual void ToVerifyTheDeleteRequestOfSettingsAPIUsingSettingsID()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To Verify the Delete request of Settings API using SettingsID", new string[] {
                        "happypath"});
#line 12
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "SettingsID"});
            table2.AddRow(new string[] {
                        "260"});
#line 13
 testRunner.Given("Provided with the valid SettingsID to be deleted.", ((string)(null)), table2, "Given ");
#line 16
 testRunner.When("I send a DELETE request to Delete settings details.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
 testRunner.Then("The settings details should be deleted.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("To Verify the POST request of Settings API", new string[] {
                "happypath"}, SourceLine=19)]
        public virtual void ToVerifyThePOSTRequestOfSettingsAPI()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To Verify the POST request of Settings API", new string[] {
                        "happypath"});
#line 20
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "EntityId",
                        "EntityType",
                        "EntityText",
                        "Address",
                        "city",
                        "state",
                        "zip",
                        "UserId",
                        "ModifiedById"});
            table3.AddRow(new string[] {
                        "605499",
                        "1",
                        "Southern Elms",
                        "4519 E 31st  Street",
                        "Tulsa",
                        "OK",
                        "74135",
                        "0",
                        "0"});
#line 21
 testRunner.Given("I have provided Entity Settings details.", ((string)(null)), table3, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "settingsID",
                        "settingType",
                        "settingValue"});
            table4.AddRow(new string[] {
                        "260",
                        "HO4",
                        "true"});
#line 24
 testRunner.And("Provided with the new SettingsInfo details.", ((string)(null)), table4, "And ");
#line 27
 testRunner.When("I send a POST request to add new settings", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 28
 testRunner.Then("The valid settings details should be saved.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("To Verify the PUT request of Settings API", new string[] {
                "happypath"}, SourceLine=30)]
        public virtual void ToVerifyThePUTRequestOfSettingsAPI()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To Verify the PUT request of Settings API", new string[] {
                        "happypath"});
#line 31
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "EntityId",
                        "EntityType",
                        "EntityText",
                        "Address",
                        "city",
                        "state",
                        "zip",
                        "UserId",
                        "ModifiedById"});
            table5.AddRow(new string[] {
                        "601234",
                        "1",
                        "BlueStone Lofts",
                        "101 Summit St",
                        "Duluth",
                        "CA",
                        "55803",
                        "-1",
                        "0"});
#line 32
 testRunner.Given("I have provided Entity Settings details for PUT Request.", ((string)(null)), table5, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "settingsID",
                        "settingType",
                        "settingValue"});
            table6.AddRow(new string[] {
                        "291",
                        "POL",
                        "true"});
#line 35
 testRunner.And("Provided with the new SettingsInfo details for PUT.", ((string)(null)), table6, "And ");
#line 38
 testRunner.When("I send a PUT request to update new settings", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
 testRunner.Then("The valid settings details should be updated.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("To Verify the GET request of Settings API using EntityID and EntityType", new string[] {
                "happypath"}, SourceLine=41)]
        public virtual void ToVerifyTheGETRequestOfSettingsAPIUsingEntityIDAndEntityType()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To Verify the GET request of Settings API using EntityID and EntityType", new string[] {
                        "happypath"});
#line 42
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "EntityID",
                        "EntityType"});
            table7.AddRow(new string[] {
                        "9277",
                        "Property"});
#line 44
 testRunner.Given("Provided with the valid EntityID and EntityType.", ((string)(null)), table7, "Given ");
#line 48
 testRunner.When("I send a GET request to fetch settings details EntityID and EntityType.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
 testRunner.Then("The valid settings details should be displayed based on EntityID and EntityType.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("To Verify the GET request of Settings API using PropertyID and PropertyType", new string[] {
                "happypath"}, SourceLine=51)]
        public virtual void ToVerifyTheGETRequestOfSettingsAPIUsingPropertyIDAndPropertyType()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("To Verify the GET request of Settings API using PropertyID and PropertyType", new string[] {
                        "happypath"});
#line 52
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyID",
                        "PropertyType"});
            table8.AddRow(new string[] {
                        "609769",
                        "LeasingDesk"});
            table8.AddRow(new string[] {
                        "2913444",
                        "Onesite"});
            table8.AddRow(new string[] {
                        "6717648",
                        "Yardi"});
#line 54
 testRunner.Given("Provided with the valid PropertyID and PropertyType.", ((string)(null)), table8, "Given ");
#line 59
 testRunner.When("I send a GET request to fetch settings details PropertyID and PropertyType.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 60
 testRunner.Then("The valid settings details should be displayed based on PropertyID and PropertyTy" +
                    "pe.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
